# Generated by Django 3.1.5 on 2021-01-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_userlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationofdocuments',
            name='addressReference',
            field=models.FileField(upload_to='media/uploads/', verbose_name='Адресная справка - с ЦОН'),
        ),
        migrations.AlterField(
            model_name='verificationofdocuments',
            name='applicationForMembership',
            field=models.FileField(upload_to='media/uploads/', verbose_name='Заявление о вступлении'),
        ),
        migrations.AlterField(
            model_name='verificationofdocuments',
            name='passportSides',
            field=models.FileField(upload_to='media/uploads/', verbose_name='Паспорт - лицевая и обратная сторона на одной странице'),
        ),
    ]
