# Generated by Django 3.1.5 on 2021-01-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_auto_20210118_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationofdocuments',
            name='documentVrf',
            field=models.CharField(choices=[('prg', 'На проверке'), ('vrf', 'Верифицирован')], default='На проверке', max_length=20),
        ),
    ]
